language: node_js
node_js:
  - '11'

services:
  - docker

before_install:
  - npm i @microservices/cli

script:
  - npx oms build
  - |
    output="$(npx oms run --silent detect -a url="https://oms.hudson.dev.s3.amazonaws.com/fixtures/73014509_538554693389505_6506989326941017176_n.jpg" | jq -c .)"
    if [ "$output" != '{"message":"Hello Peter"}' ] ; then echo "$output"; exit 1; fi
